version: "3.8"

services:
  laravel-db:
    image: mysql:8.0
    container_name: laravel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin
      MYSQL_DATABASE: proyecto
      MYSQL_USER: Laravel
      MYSQL_PASSWORD: UserLaravel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      laravel_net:
        ipv4_address: 192.168.100.5

  laravel_app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV:-development}  # Default a "development" si no está definido
    container_name: laravel_app
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      - APP_ENV=${APP_ENV:-development}
    volumes:
      - "/home/ubuntu/geoportal-laravel:/var/www/html"  # Solo en desarrollo
    depends_on:
      - laravel-db
    networks:
      laravel_net:
        ipv4_address: 192.168.100.6

volumes:
  db_data:

networks:
  laravel_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
